/**
 * Script to generate base64-encoded assets for OG images
 * Run: bunx tsx scripts/generate-og-assets.ts
 *
 * Generates:
 * - Fonts (Geist family)
 * - Logo
 * - Common UI icons
 * - Model provider icons
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT_DIR = process.cwd();
const OUTPUT_PATH = join(ROOT_DIR, 'src/lib/ui/og-assets.generated.ts');

// ============================================================================
// Font Loading
// ============================================================================

const FONTS_DIR = join(ROOT_DIR, 'public/static/fonts');
const FONT_FILES = [
  { name: 'Geist-Regular.ttf', weight: 400 },
  { name: 'Geist-SemiBold.ttf', weight: 600 },
  { name: 'Geist-Bold.ttf', weight: 700 },
  { name: 'Geist-Black.ttf', weight: 800 },
];

function loadFonts() {
  return FONT_FILES.map(({ name, weight }) => {
    const buffer = readFileSync(join(FONTS_DIR, name));
    return { name, weight, base64: buffer.toString('base64'), size: buffer.length };
  });
}

// ============================================================================
// Image Loading
// ============================================================================

function loadImageAsBase64(filePath: string): { base64: string; mimeType: string; size: number } | null {
  try {
    const buffer = readFileSync(filePath);
    const ext = filePath.split('.').pop()?.toLowerCase();
    const mimeType = ext === 'png' ? 'image/png'
      : ext === 'jpg' || ext === 'jpeg' ? 'image/jpeg'
        : ext === 'svg' ? 'image/svg+xml'
          : 'image/png';
    return {
      base64: `data:${mimeType};base64,${buffer.toString('base64')}`,
      mimeType,
      size: buffer.length,
    };
  } catch {
    return null;
  }
}

function loadImages() {
  const images: Record<string, string> = {};

  // Logo
  const logo = loadImageAsBase64(join(ROOT_DIR, 'public/static/logo.png'));
  if (logo) images.logo = logo.base64;

  // Mode icons
  const modesDir = join(ROOT_DIR, 'public/static/icons/modes');
  const modes = ['analyzing', 'brainstorming', 'debating', 'solving'];
  for (const mode of modes) {
    const icon = loadImageAsBase64(join(modesDir, `${mode}.svg`));
    if (icon) images[`mode_${mode}`] = icon.base64;
  }

  // UI icons
  const uiDir = join(ROOT_DIR, 'public/static/icons/ui');
  const uiIcons = ['robot', 'message', 'users', 'share'];
  for (const iconName of uiIcons) {
    const icon = loadImageAsBase64(join(uiDir, `${iconName}.svg`));
    if (icon) images[`ui_${iconName}`] = icon.base64;
  }

  // Model provider icons (most common ones)
  const modelsDir = join(ROOT_DIR, 'public/static/icons/ai-models');
  const providers = ['openai', 'anthropic', 'google', 'x-ai', 'deepseek', 'meta', 'openrouter'];
  for (const provider of providers) {
    const icon = loadImageAsBase64(join(modelsDir, `${provider}.png`));
    if (icon) images[`model_${provider}`] = icon.base64;
  }

  return images;
}

// ============================================================================
// Code Generation
// ============================================================================

function generateCode() {
  const fonts = loadFonts();
  const images = loadImages();

  const fontConstants = fonts
    .map((f) => `const FONT_${f.weight} = '${f.base64}';`)
    .join('\n');

  const imageConstants = Object.entries(images)
    .map(([key, value]) => `const IMG_${key.toUpperCase()} = '${value}';`)
    .join('\n');

  const imageExports = Object.keys(images)
    .map((key) => `  ${key}: IMG_${key.toUpperCase()},`)
    .join('\n');

  return `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by: scripts/generate-og-assets.ts
 *
 * Base64-encoded assets for OG image generation.
 * Embedded at build time to eliminate runtime fetching.
 */

// ============================================================================
// FONTS (Base64 encoded TTF)
// ============================================================================

${fontConstants}

function base64ToArrayBuffer(base64: string): ArrayBuffer {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes.buffer;
}

export type OGFontConfig = {
  name: string;
  data: ArrayBuffer;
  style: 'normal' | 'italic';
  weight: 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900;
};

let cachedFonts: OGFontConfig[] | null = null;

/**
 * Get OG fonts (cached, instant - no network calls)
 */
export function getOGFontsSync(): OGFontConfig[] {
  if (cachedFonts) {
    return cachedFonts;
  }

  cachedFonts = [
    { name: 'Geist', data: base64ToArrayBuffer(FONT_400), style: 'normal', weight: 400 },
    { name: 'Geist', data: base64ToArrayBuffer(FONT_600), style: 'normal', weight: 600 },
    { name: 'Geist', data: base64ToArrayBuffer(FONT_700), style: 'normal', weight: 700 },
    { name: 'Geist', data: base64ToArrayBuffer(FONT_800), style: 'normal', weight: 800 },
  ];

  return cachedFonts;
}

// ============================================================================
// IMAGES (Base64 encoded data URIs)
// ============================================================================

${imageConstants}

/**
 * Pre-embedded images for instant access (no network calls)
 */
export const OG_IMAGES = {
${imageExports}
} as const;

/**
 * Get logo as base64 data URI (instant, no fetch)
 */
export function getLogoBase64Sync(): string {
  return OG_IMAGES.logo || '';
}

/**
 * Get mode icon as base64 data URI (instant, no fetch)
 */
export function getModeIconBase64Sync(mode: string): string {
  const key = \`mode_\${mode}\` as keyof typeof OG_IMAGES;
  return OG_IMAGES[key] || OG_IMAGES.mode_analyzing || '';
}

/**
 * Get UI icon as base64 data URI (instant, no fetch)
 */
export function getUIIconBase64Sync(iconName: string): string {
  const key = \`ui_\${iconName}\` as keyof typeof OG_IMAGES;
  return OG_IMAGES[key] || '';
}

/**
 * Get model provider icon as base64 data URI (instant, no fetch)
 * Falls back to openrouter icon if provider not found
 */
export function getModelIconBase64Sync(modelId: string): string {
  // Extract provider from modelId (e.g., "openai/gpt-4" -> "openai")
  const provider = (modelId.split('/')[0] ?? modelId).toLowerCase();
  const key = \`model_\${provider}\` as keyof typeof OG_IMAGES;
  return OG_IMAGES[key] || OG_IMAGES.model_openrouter || '';
}
`;
}

// ============================================================================
// Main
// ============================================================================

const code = generateCode();
writeFileSync(OUTPUT_PATH, code);

const fonts = loadFonts();
const images = loadImages();
const totalFontSize = fonts.reduce((sum, f) => sum + f.size, 0);

console.log('Generated:', OUTPUT_PATH);
console.log('Fonts:', fonts.map((f) => `${f.weight}`).join(', '), `(${(totalFontSize / 1024).toFixed(1)} KB)`);
console.log('Images:', Object.keys(images).length, 'embedded');
