/**
 * Podcast Episode Download
 *
 * Fetches MP3 audio, embeds ID3v2.3 metadata (title, artist, album,
 * track number, copyright, cover art), and triggers a browser download
 * with a proper filename.
 */

import { BRAND } from '@/constants/brand';

import type { Id3TagOptions } from './id3-writer';
import { prependId3Tag } from './id3-writer';

// ============================================================================
// TYPES
// ============================================================================

export type DownloadEpisodeParams = {
  audioUrl: string;
  episodeNumber?: number;
  title: string;
};

// ============================================================================
// HELPERS
// ============================================================================

/** Sanitize a string for use as a filename (remove special chars, trim). */
function sanitizeFilename(str: string): string {
  return str
    .replace(/[<>:"/\\|?*]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/** Build a human-readable filename for the downloaded MP3. */
function buildFilename(title: string, episodeNumber?: number): string {
  const parts: string[] = [BRAND.name];
  if (episodeNumber !== undefined) {
    parts.push(`Ep ${episodeNumber}`);
  }
  if (title) {
    parts.push(sanitizeFilename(title));
  }
  return `${parts.join(' - ')}.mp3`;
}

/** Fetch the DebateKit logo as a Uint8Array for embedding as cover art. */
async function fetchCoverImage(): Promise<{ data: Uint8Array; mimeType: string } | undefined> {
  try {
    const response = await fetch('/static/logo.png');
    if (!response.ok) {
      return undefined;
    }
    const buffer = await response.arrayBuffer();
    return { data: new Uint8Array(buffer), mimeType: 'image/png' };
  } catch {
    return undefined;
  }
}

// ============================================================================
// PUBLIC API
// ============================================================================

/**
 * Download a podcast episode with full ID3 metadata and cover art.
 *
 * 1. Fetches the MP3 audio from the given URL
 * 2. Fetches the DebateKit logo for cover art
 * 3. Builds an ID3v2.3 tag with all metadata
 * 4. Prepends the tag to the MP3 data
 * 5. Triggers a download with a descriptive filename
 */
export async function downloadEpisode(params: DownloadEpisodeParams): Promise<void> {
  const { audioUrl, episodeNumber, title } = params;

  // Fetch audio and cover image in parallel
  const [audioResponse, coverImage] = await Promise.all([
    fetch(audioUrl),
    fetchCoverImage(),
  ]);

  if (!audioResponse.ok) {
    throw new Error(`Failed to fetch audio: ${audioResponse.status}`);
  }

  const audioBuffer = await audioResponse.arrayBuffer();
  const mp3Data = new Uint8Array(audioBuffer);

  const currentYear = String(new Date().getFullYear());

  const tagOptions: Id3TagOptions = {
    album: `${BRAND.name} Podcast`,
    artist: BRAND.name,
    comment: {
      language: 'eng',
      text: `Generated by ${BRAND.domainDisplay}`,
    },
    copyright: `${currentYear} ${BRAND.name}. All rights reserved.`,
    coverImage,
    genre: 'Podcast',
    title,
    trackNumber: episodeNumber,
    year: currentYear,
  };

  const taggedMp3 = prependId3Tag(mp3Data, tagOptions);

  // Create blob and trigger download
  const blob = new Blob([new Uint8Array(taggedMp3)], { type: 'audio/mpeg' });
  const url = URL.createObjectURL(blob);
  const filename = buildFilename(title, episodeNumber);

  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.style.display = 'none';
  document.body.appendChild(anchor);
  anchor.click();

  // Cleanup
  setTimeout(() => {
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
  }, 100);
}
