/* eslint-disable ts/no-use-before-define -- Drizzle schema requires forward references for foreign keys */
import { sql } from 'drizzle-orm';
import { check, index, integer, numeric, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const d1Migrations = sqliteTable('d1_migrations', {
  id: integer().primaryKey({ autoIncrement: true }),
  name: text(),
  appliedAt: numeric('applied_at').default(sql`(CURRENT_TIMESTAMP)`).notNull(),
}, _table => [
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const account = sqliteTable('account', {
  id: text().primaryKey().notNull(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: integer('access_token_expires_at'),
  refreshTokenExpiresAt: integer('refresh_token_expires_at'),
  scope: text(),
  password: text(),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  updatedAt: integer('updated_at').notNull(),
}, _table => [
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const apiKey = sqliteTable('api_key', {
  id: text().primaryKey().notNull(),
  name: text(),
  start: text(),
  prefix: text(),
  key: text().notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  refillInterval: integer('refill_interval'),
  refillAmount: integer('refill_amount'),
  lastRefillAt: integer('last_refill_at'),
  enabled: integer().default(true).notNull(),
  remaining: integer(),
  rateLimitEnabled: integer('rate_limit_enabled').default(true).notNull(),
  rateLimitTimeWindow: integer('rate_limit_time_window'),
  rateLimitMax: integer('rate_limit_max'),
  requestCount: integer('request_count').default(0).notNull(),
  lastRequest: integer('last_request'),
  expiresAt: integer('expires_at'),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  updatedAt: integer('updated_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  permissions: text(),
  metadata: text(),
}, _table => [
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const session = sqliteTable('session', {
  id: text().primaryKey().notNull(),
  expiresAt: integer('expires_at').notNull(),
  token: text().notNull(),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  updatedAt: integer('updated_at').notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  impersonatedBy: text('impersonated_by'),
}, table => [
  uniqueIndex('session_token_unique').on(table.token),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const user = sqliteTable('user', {
  id: text().primaryKey().notNull(),
  name: text().notNull(),
  email: text().notNull(),
  emailVerified: integer('email_verified').default(false).notNull(),
  image: text(),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  updatedAt: integer('updated_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  role: text(),
  banned: integer().default(false),
  banReason: text('ban_reason'),
  banExpires: integer('ban_expires'),
}, table => [
  uniqueIndex('user_email_unique').on(table.email),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const verification = sqliteTable('verification', {
  id: text().primaryKey().notNull(),
  identifier: text().notNull(),
  value: text().notNull(),
  expiresAt: integer('expires_at').notNull(),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  updatedAt: integer('updated_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
}, _table => [
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const stripeCustomer = sqliteTable('stripe_customer', {
  id: text().primaryKey().notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  email: text().notNull(),
  name: text(),
  defaultPaymentMethodId: text('default_payment_method_id'),
  metadata: text(),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
}, table => [
  index('stripe_customer_user_idx').on(table.userId),
  uniqueIndex('stripe_customer_user_id_unique').on(table.userId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const stripeInvoice = sqliteTable('stripe_invoice', {
  id: text().primaryKey().notNull(),
  customerId: text('customer_id').notNull().references(() => stripeCustomer.id, { onDelete: 'cascade' }),
  subscriptionId: text('subscription_id').references(() => stripeSubscription.id, { onDelete: 'set null' }),
  status: text().notNull(),
  amountDue: integer('amount_due').notNull(),
  amountPaid: integer('amount_paid').notNull(),
  currency: text().default('usd').notNull(),
  periodStart: integer('period_start'),
  periodEnd: integer('period_end'),
  hostedInvoiceUrl: text('hosted_invoice_url'),
  invoicePdf: text('invoice_pdf'),
  paid: integer().default(false).notNull(),
  attemptCount: integer('attempt_count').default(0).notNull(),
  metadata: text(),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
}, table => [
  index('stripe_invoice_status_idx').on(table.status),
  index('stripe_invoice_subscription_idx').on(table.subscriptionId),
  index('stripe_invoice_customer_idx').on(table.customerId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const stripePaymentMethod = sqliteTable('stripe_payment_method', {
  id: text().primaryKey().notNull(),
  customerId: text('customer_id').notNull().references(() => stripeCustomer.id, { onDelete: 'cascade' }),
  type: text().notNull(),
  cardBrand: text('card_brand'),
  cardLast4: text('card_last4'),
  cardExpMonth: integer('card_exp_month'),
  cardExpYear: integer('card_exp_year'),
  bankName: text('bank_name'),
  bankLast4: text('bank_last4'),
  isDefault: integer('is_default').default(false).notNull(),
  metadata: text(),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
}, table => [
  index('stripe_payment_method_default_idx').on(table.isDefault),
  index('stripe_payment_method_customer_idx').on(table.customerId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const stripePrice = sqliteTable('stripe_price', {
  id: text().primaryKey().notNull(),
  productId: text('product_id').notNull().references(() => stripeProduct.id, { onDelete: 'cascade' }),
  active: integer().default(true).notNull(),
  currency: text().default('usd').notNull(),
  unitAmount: integer('unit_amount'),
  type: text().default('recurring').notNull(),
  interval: text(),
  intervalCount: integer('interval_count').default(1),
  trialPeriodDays: integer('trial_period_days'),
  metadata: text(),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
}, table => [
  index('stripe_price_active_idx').on(table.active),
  index('stripe_price_product_idx').on(table.productId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const stripeProduct = sqliteTable('stripe_product', {
  id: text().primaryKey().notNull(),
  name: text().notNull(),
  description: text(),
  active: integer().default(true).notNull(),
  defaultPriceId: text('default_price_id'),
  metadata: text(),
  images: text(),
  features: text(),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
}, table => [
  index('stripe_product_active_idx').on(table.active),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const stripeSubscription = sqliteTable('stripe_subscription', {
  id: text().primaryKey().notNull(),
  customerId: text('customer_id').notNull().references(() => stripeCustomer.id, { onDelete: 'cascade' }),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  status: text().notNull(),
  priceId: text('price_id').notNull().references(() => stripePrice.id, { onDelete: 'cascade' }),
  quantity: integer().default(1).notNull(),
  cancelAtPeriodEnd: integer('cancel_at_period_end').default(false).notNull(),
  cancelAt: integer('cancel_at'),
  canceledAt: integer('canceled_at'),
  currentPeriodStart: integer('current_period_start').notNull(),
  currentPeriodEnd: integer('current_period_end').notNull(),
  trialStart: integer('trial_start'),
  trialEnd: integer('trial_end'),
  endedAt: integer('ended_at'),
  metadata: text(),
  version: integer().default(1).notNull(),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
}, table => [
  index('stripe_subscription_user_status_idx').on(table.userId, table.status),
  index('stripe_subscription_price_idx').on(table.priceId),
  index('stripe_subscription_status_idx').on(table.status),
  index('stripe_subscription_user_idx').on(table.userId),
  index('stripe_subscription_customer_idx').on(table.customerId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const stripeWebhookEvent = sqliteTable('stripe_webhook_event', {
  id: text().primaryKey().notNull(),
  type: text().notNull(),
  apiVersion: text('api_version'),
  processed: integer().default(false).notNull(),
  processingError: text('processing_error'),
  data: text(),
  createdAt: integer('created_at').notNull(),
  processedAt: integer('processed_at'),
}, table => [
  index('stripe_webhook_event_processed_idx').on(table.processed),
  index('stripe_webhook_event_type_idx').on(table.type),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const chatCustomRole = sqliteTable('chat_custom_role', {
  id: text().primaryKey().notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  name: text().notNull(),
  description: text(),
  systemPrompt: text('system_prompt'),
  metadata: text(),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  updatedAt: integer('updated_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
}, table => [
  index('chat_custom_role_name_idx').on(table.name),
  index('chat_custom_role_user_idx').on(table.userId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const chatMessage = sqliteTable('chat_message', {
  id: text().primaryKey().notNull(),
  threadId: text('thread_id').notNull().references(() => chatThread.id, { onDelete: 'cascade' }),
  participantId: text('participant_id').references(() => chatParticipant.id, { onDelete: 'set null' }),
  role: text().default('assistant').notNull(),
  parts: text().notNull(),
  roundNumber: integer('round_number').default(0).notNull(),
  toolCalls: text('tool_calls'),
  metadata: text(),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
}, table => [
  index('chat_message_thread_round_idx').on(table.threadId, table.roundNumber),
  index('chat_message_thread_created_idx').on(table.threadId, table.createdAt),
  index('chat_message_role_idx').on(table.role),
  index('chat_message_participant_idx').on(table.participantId),
  index('chat_message_created_idx').on(table.createdAt),
  index('chat_message_thread_idx').on(table.threadId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const chatParticipant = sqliteTable('chat_participant', {
  id: text().primaryKey().notNull(),
  threadId: text('thread_id').notNull().references(() => chatThread.id, { onDelete: 'cascade' }),
  modelId: text('model_id').notNull(),
  customRoleId: text('custom_role_id').references(() => chatCustomRole.id, { onDelete: 'set null' }),
  role: text(),
  priority: integer().default(0).notNull(),
  isEnabled: integer('is_enabled').default(true).notNull(),
  settings: text(),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  updatedAt: integer('updated_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
}, table => [
  uniqueIndex('chat_participant_thread_model_unique').on(table.threadId, table.modelId),
  index('chat_participant_custom_role_idx').on(table.customRoleId),
  index('chat_participant_priority_idx').on(table.priority),
  index('chat_participant_thread_idx').on(table.threadId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const chatPreSearch = sqliteTable('chat_pre_search', {
  id: text().primaryKey().notNull(),
  threadId: text('thread_id').notNull().references(() => chatThread.id, { onDelete: 'cascade' }),
  roundNumber: integer('round_number').notNull(),
  userQuery: text('user_query').notNull(),
  status: text().default('pending').notNull(),
  searchData: text('search_data'),
  errorMessage: text('error_message'),
  completedAt: integer('completed_at'),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
}, table => [
  uniqueIndex('chat_pre_search_thread_round_unique').on(table.threadId, table.roundNumber),
  index('chat_pre_search_status_idx').on(table.status),
  index('chat_pre_search_created_idx').on(table.createdAt),
  index('chat_pre_search_round_idx').on(table.threadId, table.roundNumber),
  index('chat_pre_search_thread_idx').on(table.threadId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const chatThread = sqliteTable('chat_thread', {
  id: text().primaryKey().notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  projectId: text('project_id').references(() => chatProject.id, { onDelete: 'set null' }),
  title: text().notNull(),
  slug: text().notNull(),
  previousSlug: text('previous_slug'),
  mode: text().default('debating').notNull(),
  status: text().default('active').notNull(),
  isFavorite: integer('is_favorite').default(false).notNull(),
  isPublic: integer('is_public').default(false).notNull(),
  isAiGeneratedTitle: integer('is_ai_generated_title').default(false).notNull(),
  enableWebSearch: integer('enable_web_search').default(false).notNull(),
  metadata: text(),
  version: integer().default(1).notNull(),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  updatedAt: integer('updated_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  lastMessageAt: integer('last_message_at'),
}, table => [
  index('chat_thread_public_status_idx').on(table.isPublic, table.status),
  index('chat_thread_public_idx').on(table.isPublic),
  index('chat_thread_favorite_idx').on(table.isFavorite),
  index('chat_thread_previous_slug_idx').on(table.previousSlug),
  index('chat_thread_slug_idx').on(table.slug),
  index('chat_thread_updated_idx').on(table.updatedAt),
  index('chat_thread_status_idx').on(table.status),
  index('chat_thread_project_idx').on(table.projectId),
  index('chat_thread_user_idx').on(table.userId),
  uniqueIndex('chat_thread_slug_unique').on(table.slug),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const chatThreadChangelog = sqliteTable('chat_thread_changelog', {
  id: text().primaryKey().notNull(),
  threadId: text('thread_id').notNull().references(() => chatThread.id, { onDelete: 'cascade' }),
  roundNumber: integer('round_number').default(0).notNull(),
  changeType: text('change_type').notNull(),
  changeSummary: text('change_summary').notNull(),
  changeData: text('change_data').notNull(),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
}, table => [
  index('chat_thread_changelog_thread_round_idx').on(table.threadId, table.roundNumber),
  index('chat_thread_changelog_created_idx').on(table.createdAt),
  index('chat_thread_changelog_type_idx').on(table.changeType),
  index('chat_thread_changelog_thread_idx').on(table.threadId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const chatUserPreset = sqliteTable('chat_user_preset', {
  id: text().primaryKey().notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  name: text().notNull(),
  mode: text().default('debating').notNull(),
  modelRoles: text('model_roles').notNull(),
  metadata: text(),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  updatedAt: integer('updated_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
}, table => [
  index('chat_user_preset_name_idx').on(table.name),
  index('chat_user_preset_user_idx').on(table.userId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const creditTransaction = sqliteTable('credit_transaction', {
  id: text().primaryKey().notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  type: text().notNull(),
  amount: integer().notNull(),
  balanceAfter: integer('balance_after').notNull(),
  inputTokens: integer('input_tokens'),
  outputTokens: integer('output_tokens'),
  totalTokens: integer('total_tokens'),
  creditsUsed: integer('credits_used'),
  threadId: text('thread_id').references(() => chatThread.id, { onDelete: 'set null' }),
  messageId: text('message_id'),
  streamId: text('stream_id'),
  action: text(),
  modelId: text('model_id'),
  modelPricingInputPerMillion: integer('model_pricing_input_per_million'),
  modelPricingOutputPerMillion: integer('model_pricing_output_per_million'),
  description: text(),
  metadata: text(),
  createdAt: integer('created_at').notNull(),
}, table => [
  index('credit_tx_user_type_idx').on(table.userId, table.type),
  index('credit_tx_user_created_idx').on(table.userId, table.createdAt),
  index('credit_tx_action_idx').on(table.action),
  index('credit_tx_stream_idx').on(table.streamId),
  index('credit_tx_thread_idx').on(table.threadId),
  index('credit_tx_created_idx').on(table.createdAt),
  index('credit_tx_type_idx').on(table.type),
  index('credit_tx_user_idx').on(table.userId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const userCreditBalance = sqliteTable('user_credit_balance', {
  id: text().primaryKey().notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  balance: integer().default(0).notNull(),
  reservedCredits: integer('reserved_credits').default(0).notNull(),
  planType: text('plan_type').default('free').notNull(),
  monthlyCredits: integer('monthly_credits').default(0).notNull(),
  lastRefillAt: integer('last_refill_at'),
  nextRefillAt: integer('next_refill_at'),
  version: integer().default(1).notNull(),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
}, table => [
  index('user_credit_balance_next_refill_idx').on(table.nextRefillAt),
  index('user_credit_balance_user_idx').on(table.userId),
  uniqueIndex('user_credit_balance_user_id_unique').on(table.userId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const chatProject = sqliteTable('chat_project', {
  id: text().primaryKey().notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  name: text().notNull(),
  description: text(),
  color: text().default('blue'),
  customInstructions: text('custom_instructions'),
  autoragInstanceId: text('autorag_instance_id'),
  r2FolderPrefix: text('r2_folder_prefix').notNull(),
  settings: text(),
  metadata: text(),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  updatedAt: integer('updated_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  icon: text().default('briefcase'),
}, table => [
  index('chat_project_name_idx').on(table.name),
  index('chat_project_created_idx').on(table.createdAt),
  index('chat_project_user_idx').on(table.userId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const projectAttachment = sqliteTable('project_attachment', {
  id: text().primaryKey().notNull(),
  projectId: text('project_id').notNull().references(() => chatProject.id, { onDelete: 'cascade' }),
  uploadId: text('upload_id').notNull().references(() => upload.id, { onDelete: 'cascade' }),
  indexStatus: text('index_status').default('pending').notNull(),
  ragMetadata: text('rag_metadata'),
  addedBy: text('added_by').notNull().references(() => user.id, { onDelete: 'cascade' }),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  updatedAt: integer('updated_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
}, table => [
  uniqueIndex('project_attachment_unique_idx').on(table.projectId, table.uploadId),
  index('project_attachment_created_idx').on(table.createdAt),
  index('project_attachment_added_by_idx').on(table.addedBy),
  index('project_attachment_status_idx').on(table.indexStatus),
  index('project_attachment_upload_idx').on(table.uploadId),
  index('project_attachment_project_idx').on(table.projectId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const projectMemory = sqliteTable('project_memory', {
  id: text().primaryKey().notNull(),
  projectId: text('project_id').notNull().references(() => chatProject.id, { onDelete: 'cascade' }),
  content: text().notNull(),
  summary: text(),
  source: text().default('chat').notNull(),
  sourceThreadId: text('source_thread_id').references(() => chatThread.id, { onDelete: 'set null' }),
  sourceRoundNumber: integer('source_round_number'),
  importance: integer().default(5).notNull(),
  isActive: integer('is_active').default(true).notNull(),
  metadata: text(),
  createdBy: text('created_by').notNull().references(() => user.id, { onDelete: 'cascade' }),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  updatedAt: integer('updated_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
}, table => [
  index('project_memory_project_active_importance_idx').on(table.projectId, table.isActive, table.importance),
  index('project_memory_created_idx').on(table.createdAt),
  index('project_memory_importance_idx').on(table.importance),
  index('project_memory_active_idx').on(table.isActive),
  index('project_memory_thread_idx').on(table.sourceThreadId),
  index('project_memory_source_idx').on(table.source),
  index('project_memory_project_idx').on(table.projectId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const messageUpload = sqliteTable('message_upload', {
  id: text().primaryKey().notNull(),
  messageId: text('message_id').notNull().references(() => chatMessage.id, { onDelete: 'cascade' }),
  uploadId: text('upload_id').notNull().references(() => upload.id, { onDelete: 'cascade' }),
  displayOrder: integer('display_order').default(0).notNull(),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
}, table => [
  uniqueIndex('message_upload_unique_idx').on(table.messageId, table.uploadId),
  index('message_upload_created_idx').on(table.createdAt),
  index('message_upload_upload_idx').on(table.uploadId),
  index('message_upload_message_idx').on(table.messageId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const threadUpload = sqliteTable('thread_upload', {
  id: text().primaryKey().notNull(),
  threadId: text('thread_id').notNull().references(() => chatThread.id, { onDelete: 'cascade' }),
  uploadId: text('upload_id').notNull().references(() => upload.id, { onDelete: 'cascade' }),
  context: text(),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
}, table => [
  uniqueIndex('thread_upload_unique_idx').on(table.threadId, table.uploadId),
  index('thread_upload_created_idx').on(table.createdAt),
  index('thread_upload_upload_idx').on(table.uploadId),
  index('thread_upload_thread_idx').on(table.threadId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const upload = sqliteTable('upload', {
  id: text().primaryKey().notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  filename: text().notNull(),
  r2Key: text('r2_key').notNull(),
  fileSize: integer('file_size').notNull(),
  mimeType: text('mime_type').notNull(),
  status: text().default('uploaded').notNull(),
  metadata: text(),
  createdAt: integer('created_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
  updatedAt: integer('updated_at').default(sql`(cast((julianday('now') - 2440587.5)*86400000 as integer))`).notNull(),
}, table => [
  index('upload_mime_type_idx').on(table.mimeType),
  index('upload_r2_key_idx').on(table.r2Key),
  index('upload_created_idx').on(table.createdAt),
  index('upload_status_idx').on(table.status),
  index('upload_user_idx').on(table.userId),
  uniqueIndex('upload_r2_key_unique').on(table.r2Key),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const userChatUsage = sqliteTable('user_chat_usage', {
  id: text().primaryKey().notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  currentPeriodStart: integer('current_period_start').notNull(),
  currentPeriodEnd: integer('current_period_end').notNull(),
  threadsCreated: integer('threads_created').default(0).notNull(),
  messagesCreated: integer('messages_created').default(0).notNull(),
  customRolesCreated: integer('custom_roles_created').default(0).notNull(),
  analysisGenerated: integer('analysis_generated').default(0).notNull(),
  subscriptionTier: text('subscription_tier').default('free').notNull(),
  isAnnual: integer('is_annual').default(false).notNull(),
  pendingTierChange: text('pending_tier_change'),
  pendingTierIsAnnual: integer('pending_tier_is_annual'),
  version: integer().default(1).notNull(),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
}, table => [
  index('user_chat_usage_period_idx').on(table.currentPeriodEnd),
  index('user_chat_usage_user_idx').on(table.userId),
  uniqueIndex('user_chat_usage_user_id_unique').on(table.userId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const userChatUsageHistory = sqliteTable('user_chat_usage_history', {
  id: text().primaryKey().notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  periodStart: integer('period_start').notNull(),
  periodEnd: integer('period_end').notNull(),
  threadsCreated: integer('threads_created').default(0).notNull(),
  messagesCreated: integer('messages_created').default(0).notNull(),
  customRolesCreated: integer('custom_roles_created').default(0).notNull(),
  analysisGenerated: integer('analysis_generated').default(0).notNull(),
  subscriptionTier: text('subscription_tier').notNull(),
  isAnnual: integer('is_annual').default(false).notNull(),
  createdAt: integer('created_at').notNull(),
}, table => [
  index('user_chat_usage_history_period_idx').on(table.periodStart, table.periodEnd),
  index('user_chat_usage_history_user_idx').on(table.userId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const automatedJob = sqliteTable('automated_job', {
  id: text().primaryKey().notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  threadId: text('thread_id').references(() => chatThread.id, { onDelete: 'set null' }),
  initialPrompt: text('initial_prompt').notNull(),
  totalRounds: integer('total_rounds').default(3).notNull(),
  currentRound: integer('current_round').default(0).notNull(),
  autoPublish: integer('auto_publish').default(false).notNull(),
  status: text().default('pending').notNull(),
  selectedModels: text('selected_models'),
  metadata: text(),
  createdAt: integer('created_at').default(sql`(unixepoch() * 1000)`).notNull(),
  updatedAt: integer('updated_at').default(sql`(unixepoch() * 1000)`).notNull(),
}, table => [
  index('automated_job_created_idx').on(table.createdAt),
  index('automated_job_thread_idx').on(table.threadId),
  index('automated_job_status_idx').on(table.status),
  index('automated_job_user_idx').on(table.userId),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);

export const deletedAccountAudit = sqliteTable('deleted_account_audit', {
  id: text().primaryKey().notNull(),
  emailHash: text('email_hash').notNull(),
  deletionCount: integer('deletion_count').default(1).notNull(),
  firstDeletedAt: integer('first_deleted_at').notNull(),
  lastDeletedAt: integer('last_deleted_at').notNull(),
}, table => [
  index('deleted_account_audit_email_hash_idx').on(table.emailHash),
  uniqueIndex('deleted_account_audit_email_hash_unique').on(table.emailHash),
  check('check_priority_non_negative', sql`"chat_participant"."priority" >= 0`),
  check('check_balance_non_negative', sql`"user_credit_balance"."balance" >= 0`),
  check('check_reserved_non_negative', sql`"user_credit_balance"."reserved_credits" >= 0`),
  check('check_monthly_credits_non_negative', sql`"user_credit_balance"."monthly_credits" >= 0`),
  check('check_version_positive', sql`"user_chat_usage"."version" > 0`),
  check('check_threads_non_negative', sql`"user_chat_usage"."threads_created" >= 0`),
  check('check_messages_non_negative', sql`"user_chat_usage"."messages_created" >= 0`),
  check('check_custom_roles_non_negative', sql`"user_chat_usage"."custom_roles_created" >= 0`),
  check('check_analysis_non_negative', sql`"user_chat_usage"."analysis_generated" >= 0`),
  check('check_period_order', sql`"user_chat_usage"."current_period_end" > "user_chat_usage"."current_period_start"`),
  check('check_history_threads_non_negative', sql`"user_chat_usage_history"."threads_created" >= 0`),
  check('check_history_messages_non_negative', sql`"user_chat_usage_history"."messages_created" >= 0`),
  check('check_history_custom_roles_non_negative', sql`"user_chat_usage_history"."custom_roles_created" >= 0`),
  check('check_history_analysis_non_negative', sql`"user_chat_usage_history"."analysis_generated" >= 0`),
  check('check_history_period_order', sql`"user_chat_usage_history"."period_end" > "user_chat_usage_history"."period_start"`),
]);
